<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>lk.dcd</groupId>
        <artifactId>Globaltrade-Logistics-System</artifactId>
        <version>1.0</version>
    </parent>

    <artifactId>globaltrade-ear</artifactId>
    <packaging>ear</packaging>

    <dependencies>

        <dependency>
            <groupId>lk.dcd</groupId>
            <artifactId>globaltrade-ejb</artifactId>
            <version>1.0</version>
            <type>ejb</type>
        </dependency>

       
        <dependency>
            <groupId>lk.dcd</groupId>
            <artifactId>globaltrade-web</artifactId>
            <version>1.0</version>
            <type>war</type>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <version>8</version>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <modules>
                        <webModule>
                            <groupId>lk.dcd</groupId>
                            <artifactId>globaltrade-web</artifactId>
                            <contextRoot>/globaltrade</contextRoot>
                        </webModule>
                    </modules>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>